### ISSUE TITLE
Outputs the wrong filenames when pylint is given a directory name

### ISSUE THREAD

**Issue by dannystaple** [tgamauf/pylint-pycharm#1]
If you give this a parameter that is a path, pylint will correctly find problems/errors in the files.
However, it will then append the parent dir of the path to those filenames, not the path specified.

```
/home/stapled/python_envs/env2/bin/pylint-pycharm --virtualenv=/home/stapled/python_envs/env2 /home/stapled/workspace/project/syslib/FlashLib
/home/stapled/workspace/project/syslib/USBFlashingCommon.py:38:0: [I] Locally disabling W0703
/home/stapled/workspace/project/syslib/USBFlashingCommon.py:64:0: [C, make_sfg_flasher._flashAndReboot] Missing docstring
/home/stapled/workspace/project/syslib/SerialStateTree.py:133:0: [I] Locally disabling E0702
/home/stapled/workspace/project/syslib/SerialStateTree.py:31:0: [R, SerStateTreeParser.addTransition] Too many arguments (9/5)
/home/stapled/workspace/project/syslib/SerialStateTree.py:63:0: [W, SerStateTreeParser._doCallBack] Catching too general exception Exception
```

In the above example - the files are structured this way (snipped for relevance)

```
project
\- syslib
    \- FlashLib
        \- USBFlashingCommon.py
        \- SerialStateTree.py
        \- ...
...
```

**Comment by dupuy** [comment]
I had the opposite version of this problem, which was that one of the directory components was being duplicated in the generated pathnames (rather than being omitted).

The problem is due to a misunderstanding about the way that pylint prints module paths - it simply generates paths relative to the current directory - the package/module path as passed to it is entirely irrelevant.

In my develop branch I have a [commit](https://github.com/dupuy/pylint-pycharm/commit/93405d8571512c9ee80aa0576fe7202ed34a2dc6) that fixes pylint-pycharm to do the right thing in both our cases.  I've made some other changes in the master on which it is based, so it might not apply cleanly to your fork, but it is mostly removing the unused (except for tests) get_root_path() function, which isn't really needed - as well as the tests that did use it, and setting root_path to `os.path.realpath(os.path.abspath("."))`.

**Comment by tgamauf** [comment]
Considering the age and my redesign, this probably not relevant anymore. Please open a new issue if you run into troubles.
